language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic
    - COMPOSER_DISCARD_CHANGES=true
    - COMPOSER_NO_INTERACTION=1
    - COMPOSER_DISABLE_XDEBUG_WARN=1

cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.composer/cache
    - $HOME/.npm

before_install:
  - nvm install node

install:
  - composer install --prefer-dist
  - npm install -g gulp
  - npm install

before_script:
  - cp .env.travis .env
  - gulp --production

script:
  - vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: change
