language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic
    - COMPOSER_DISCARD_CHANGES=true
    - COMPOSER_NO_INTERACTION=1
    - COMPOSER_DISABLE_XDEBUG_WARN=1
    - TRAVIS_NODE_VERSION="5"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - node -V

install:
  - composer update --prefer-dist
  - npm install -g gulp
  - npm install

before_script:
  - gulp --production

script:
  - vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: change
