language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm
  
node_js:
  - "5"
  - "5.1"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer update --prefer-dist
  - travis_retry npm install
  - gulp --production

script:
  - vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: change
